# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='refer',
            field=models.CharField(max_length=128, verbose_name='refer'),
        ),
    ]
