# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_auto_20200519_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishes',
            old_name='IP',
            new_name='ip',
        ),
        migrations.AddField(
            model_name='fishes',
            name='x_forwarded_for',
            field=models.CharField(default='', max_length=128, verbose_name='x_forwarded_for'),
            preserve_default=False,
        ),
    ]
