# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0003_auto_20200520_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='fishes',
            name='refer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='refer'),
        ),
        migrations.AlterField(
            model_name='fishes',
            name='user_agent',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='UA'),
        ),
        migrations.AlterField(
            model_name='fishes',
            name='x_forwarded_for',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='x_forwarded_for'),
        ),
    ]
